<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Targeting netstandard2.0 ensures it runs on both ancient .NET Framework 4.6+ and modern .NET 8 -->
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    
    <!-- NuGet Publishing Meta -->
    <PackageId>SnerdMQ</PackageId>
    <Version>0.4.1</Version>
    <Authors>Greyhands2</Authors>
    <Company>Greyhands2</Company>
    <Description>A zero-config, C-speed background job queue for the .NET ecosystem. Ditch Redis for an embedded Rust daemon.</Description>
    <RepositoryUrl>https://github.com/speed-nerd/snerdmq-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
